language: node_js
sudo: required
node_js:
  - "node"

cache:
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.0
  - export PATH="$HOME/.yarn/bin:$PATH"
  - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

install:
  - yarn
  - npm install -g lerna

script:
  - yarn build

deploy:
  - provider: pages
    local-dir: public
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    target-branch: gh-pages
    fqdn: ui.vida-lisboa.pt
    on:
      branch: master
